# Generated by Django 5.2 on 2025-04-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_1_date', models.DateField()),
                ('dose_2_date', models.DateField(blank=True)),
            ],
        ),
    ]
